version: '3.8'
services:
  backend:
    build: 
      context: .
    image: mlapp:v1
    ports:
      - '8000:8000'
    command: ["uvicorn", "backend:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]