DATASET:
  PATH: "Dataset/creditcard.csv"
MODEL:
  NAME: "FRAUD_CLASSIFIER"
  SAVE_LOCAL: False
  SAVE_FOLDER: "weights"
MLFLOW:
  EXPERIMENT_NAME: "CREDITCARD_FRAUD_CLASSIFIER"
  MLFLOW_TRACKING_URI: "http://127.0.0.1:5000"
  SAVE_MODEL_REGISTRY: True
PARAMETERS:
  SPLIT_RATIO: 0.9
